### ISSUE TITLE
'wrong profile hash' message is shown incorrectly in live and testnet

### ISSUE THREAD

**Issue by CriptoGirl** [byteball/ocore#248]
private_profile.js line 60 'wrong profile hash' message is triggered when I try to save a private profile to my wallet at the end of the attestation process.
I thought it was an issue with my code, but Tarmo said that he 'noticed that Real Name Attestation is broken also' in both live and testnet. 
This is really urgent, as I am trying to complete a working prototype for submission to a UK Gov tender due next week.

**Comment by tonyofbyteball** [comment]
Try to set bJsonBased to false on this line https://github.com/byteball/ocore/blob/master/private_profile.js#L44 and let me know if it helps.

**Comment by CriptoGirl** [comment]
I have changed my code to provide 'true' parameter in the objectHash.getBase64Hash function calls and now it all working fine.  Thank you for looking into this for me.
